export const PNG_ICONS = {
  activity: require('@/assets/icons/activity (1).png'),
  alert: require('@/assets/icons/alert.png'),
  analytics: require('@/assets/icons/Analytics.png'),
  attendance: require('@/assets/icons/attendance.png'),
  axe: require('@/assets/icons/mine.png'),
  notification: require('@/assets/icons/notification.png'),
  boy: require('@/assets/icons/boy.png'),
  briefcase: require('@/assets/icons/briefcase (1).png'),
  bulb: require('@/assets/icons/bulb.png'),
  calculator: require('@/assets/icons/calculator.png'),
  pending: require('@/assets/icons/pending.png'),
  camera: require('@/assets/icons/camera.png'),
  chat: require('@/assets/icons/chat.png'),
  compliance: require('@/assets/icons/compliance.png'),
  cube: require('@/assets/icons/cube.png'),
  'cube-dynamic': require('@/assets/icons/cube-dynamic-color.png'),
  down: require('@/assets/icons/down.png'),
  'file-archive': require('@/assets/icons/file-archive-new.png'),
  'file-image': require('@/assets/icons/file-image (1).png'),
  'file-pdf': require('@/assets/icons/file-pdf (1).png'),
  'file-pie-chart': require('@/assets/icons/file-pie-chart (1).png'),
  'file-text': require('@/assets/icons/file-text.png'),
  flag: require('@/assets/icons/flag (1).png'),
  ghost: require('@/assets/icons/ghost.png'),
  gloves: require('@/assets/icons/gloves.png'),
  hammer: require('@/assets/icons/hammer.png'),
  'hard-hat': require('@/assets/icons/hard-hat.png'),
  heart: require('@/assets/icons/heart.png'),
  help: require('@/assets/icons/help.png'),
  home: require('@/assets/icons/home.png'),
  info: require('@/assets/icons/info (1).png'),
  inspection: require('@/assets/icons/inspection.png'),
  key: require('@/assets/icons/key.png'),
  landmark: require('@/assets/icons/landmark (1).png'),
  leaf: require('@/assets/icons/leaf.png'),
  location: require('@/assets/icons/location.png'),
  lock: require('@/assets/icons/lock.png'),
  locker: require('@/assets/icons/locker.png'),
  map: require('@/assets/icons/map.png'),
  mail: require('@/assets/icons/mail.png'),
  'map-pin': require('@/assets/icons/map-pin.png'),
  mine: require('@/assets/icons/mine.png'),
  more: require('@/assets/icons/more.png'),
  mountain: require('@/assets/icons/mountain.png'),
  navigation: require('@/assets/icons/navigation (1).png'),
  notebook: require('@/assets/icons/notebook.png'),
  'notify-heart': require('@/assets/icons/notify-heart.png'),
  overdue: require('@/assets/icons/overdue.png'),
  open: require('@/assets/icons/open.png'),
  picture: require('@/assets/icons/picture.png'),
  plus: require('@/assets/icons/plus.png'),
  'plus-circle': require('@/assets/icons/plus-circle (1).png'),
  report: require('@/assets/icons/report.png'),
  right: require('@/assets/icons/right.png'),
  'report-incident': require('@/assets/icons/report incident.png'),
  rocket: require('@/assets/icons/rocket.png'),
  search: require('@/assets/icons/search (1).png'),
  setting: require('@/assets/icons/setting.png'),
  shield: require('@/assets/icons/shield-dynamic-color.png'),
  skull: require('@/assets/icons/risk.png'),
  sphere: require('@/assets/icons/sphere-dynamic-color.png'),
  star: require('@/assets/icons/star.png'),
  sync: require('@/assets/icons/sync.png'),
  target: require('@/assets/icons/target-dynamic-color.png'),
  tools: require('@/assets/icons/tools.png'),
  'trash-can': require('@/assets/icons/trash-can.png'),
  travel: require('@/assets/icons/travel.png'),
  up: require('@/assets/icons/up.png'),
  'user-check': require('@/assets/icons/user-check (1).png'),
  wrench: require('@/assets/icons/wrench.png'),
} as const;

export type PngIconName = keyof typeof PNG_ICONS;