import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ClientSession, Types } from "mongoose";
import Evidence from "../models/Evidence.js";
import { logAction } from "./auditLogger.js";
import { sessionOption } from "./outboxService.js";
import type { EvidenceSourceType, IntegrityStatus } from "../types/index.js";

// ── Feature 05: Evidence Integrity service ───────────────────────────────────
// Server-side SHA-256 at ingest + deterministic re-verification.
//   - contentHash is computed ONLY from the bytes the server received
//     (req.file.buffer) — never from a client-supplied value (edge G3).
//   - verification re-reads the STORED bytes (untransformed Cloudinary original
//     URL, or the persisted local file) and compares against contentHash.
//   - identity is the content hash, never the URL (edge C).

// Local-mode uploads persist the exact received buffer to this directory so
// verification is real (re-read the file, not a placeholder URL). Overridable
// via EVIDENCE_UPLOADS_DIR; resolved against the server cwd (backend/).
export const UPLOADS_DIR = path.resolve(
  process.env.EVIDENCE_UPLOADS_DIR ?? path.join(process.cwd(), "uploads")
);

// Sentinel for rows whose upload failed (edge G): there is NO stored file, so
// verificationSource would have nothing to point at. The sentinel keeps the
// field non-empty (schema `required`) while remaining truthful — verifyEvidence
// short-circuits on UPLOAD_FAILED before ever reading it.
export const UPLOAD_FAILED_SENTINEL = "UPLOAD_FAILED:no-stored-file";

// ── SHA-256 of the exact received bytes (edges A/F/G3) ───────────────────────
export function sha256Hex(data: Buffer): string {
  return createHash("sha256").update(data).digest("hex");
}

// ── Cloudinary original-URL builder (edge G1) ────────────────────────────────
// Uploads use quality:"auto" / fetch_format:"auto", which store an INCOMING
// transformation — the delivered secure_url is NOT byte-identical to the
// master. Verification must fetch the untransformed original so the recompute
// equals the upload hash. The original deliver URL is a pure template:
// https://res.cloudinary.com/<cloud_name>/image/upload/<public_id>
// (no transformation params) → serves the master bytes verbatim. Built as a
// plain string (no SDK call) so it works in every process without
// connectCloudinary() — the SDK's configured delivery_name is exactly this.
export function buildCloudinaryOriginalUrl(publicId: string): string {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME ?? "agnistrot";
  return `https://res.cloudinary.com/${cloudName}/image/upload/${publicId}`;
}

// ── Local-mode persistence ───────────────────────────────────────────────────
// Writes the exact buffer to disk under <UPLOADS_DIR>/<evidenceId>-<safeName>
// and returns the absolute path (the verification source for kind "file").
export async function persistLocalFile(
  id: Types.ObjectId,
  buffer: Buffer,
  originalName: string
): Promise<string> {
  const safeName = originalName.replace(/[^\w.-]/g, "_");
  await mkdir(UPLOADS_DIR, { recursive: true });
  const abs = path.join(UPLOADS_DIR, `${id.toString()}-${safeName}`);
  await writeFile(abs, buffer);
  return abs;
}

export async function readLocalFile(absPath: string): Promise<Buffer> {
  return readFile(absPath);
}

// ── Record an evidence row ───────────────────────────────────────────────────

export type RecordEvidenceInput = {
  _id: Types.ObjectId;                 // pre-generated by the controller so the
                                       // persisted filename is stable pre-upload
  sourceType: EvidenceSourceType;
  sourceRecordId?: Types.ObjectId;
  siteId: Types.ObjectId;
  fileUrl: string;
  verificationSource: string;
  verificationSourceKind: "url" | "file";
  contentHash?: string;                // absent = hashing failed → unverified (edge H)
  fileName?: string;
  uploadedBy: Types.ObjectId;
  uploadedAt?: Date;
  integrityStatus?: IntegrityStatus;   // default "unverified"
  verificationNote?: string;
};

// Creates the evidence row (optionally inside the caller's transaction — the
// document ingest writes document + evidence + outbox event atomically) and
// appends a hash-chained audit entry. The audit action reflects the record's
// state: "ingested" for a stored file, "upload_failed" for edge G rows.
export async function createEvidence(
  input: RecordEvidenceInput,
  session?: ClientSession | null
): Promise<import("mongoose").HydratedDocument<import("../types/index.js").IEvidence>> {
  const [ev] = await Evidence.create(
    [
      {
        _id: input._id,
        sourceType: input.sourceType,
        ...(input.sourceRecordId ? { sourceRecordId: input.sourceRecordId } : {}),
        siteId: input.siteId,
        fileUrl: input.fileUrl,
        verificationSource: input.verificationSource,
        verificationSourceKind: input.verificationSourceKind,
        ...(input.contentHash ? { contentHash: input.contentHash } : {}),
        ...(input.fileName ? { fileName: input.fileName } : {}),
        uploadedBy: input.uploadedBy,
        uploadedAt: input.uploadedAt ?? new Date(),
        integrityStatus: input.integrityStatus ?? "unverified",
        ...(input.verificationNote ? { verificationNote: input.verificationNote } : {}),
      },
    ],
    sessionOption(session)
  );
  if (!ev) throw new Error("Evidence creation returned no result.");

  await logAction({
    entityType: "evidence",
    entityId: ev._id,
    action: input.integrityStatus === "UPLOAD_FAILED" ? "upload_failed" : "ingested",
    actorId: input.uploadedBy,
    payload: {
      sourceType: input.sourceType,
      ...(input.contentHash ? { contentHash: input.contentHash } : {}),
      integrityStatus: ev.integrityStatus,
      siteId: input.siteId.toString(),
    },
  });

  return ev;
}

// ── Fetch the stored bytes of an evidence row ────────────────────────────────
// Local mode reads the persisted disk file; Cloudinary mode fetches the
// untransformed original URL. Any failure → unavailable (edge G), with the
// reason recorded — we never guess a MATCH from a failed read.
async function resolveBytes(ev: {
  verificationSourceKind: "url" | "file";
  verificationSource: string;
}): Promise<{ ok: true; bytes: Buffer } | { ok: false; reason: string }> {
  try {
    if (ev.verificationSourceKind === "file") {
      return { ok: true, bytes: await readLocalFile(ev.verificationSource) };
    }
    const src = ev.verificationSource;
    if (!/^https?:\/\//.test(src)) {
      return { ok: false, reason: "invalid verification source" };
    }
    const res = await fetch(src, { signal: AbortSignal.timeout(15_000) });
    if (!res.ok) return { ok: false, reason: `fetch failed: HTTP ${res.status}` };
    return { ok: true, bytes: Buffer.from(await res.arrayBuffer()) };
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : String(err) };
  }
}

// ── Verify one evidence row ──────────────────────────────────────────────────
// Re-reads the stored bytes, recomputes SHA-256, compares to contentHash:
//   MATCH            → verified
//   bytes differ     → INTEGRITY_MISMATCH (edge B)
//   source unreadable→ unavailable (edge G)
//   no contentHash   → stays unverified with "no baseline" (edges H + G2 —
//                      NEVER flagged as tampered)
//   UPLOAD_FAILED    → stays UPLOAD_FAILED (no stored file to compare — edge G)
export interface VerifyOutcome {
  id: string;
  integrityStatus: IntegrityStatus;
  checkCount: number;
  lastVerifiedAt: Date;
  verificationNote: string | null;
}

export async function verifyEvidence(
  id: Types.ObjectId,
  actorId?: Types.ObjectId
): Promise<VerifyOutcome | null> {
  const ev = await Evidence.findById(id);
  if (!ev) return null;

  const now = new Date();
  let status = ev.integrityStatus;
  let note = ev.verificationNote ?? null;

  if (ev.integrityStatus === "UPLOAD_FAILED") {
    note = "Cannot verify: upload failed — no stored file to compare.";
  } else if (!ev.contentHash) {
    status = "unverified";
    note = "No baseline: no content hash recorded for this evidence.";
  } else {
    const resolved = await resolveBytes(ev);
    if (!resolved.ok) {
      status = "unavailable";
      note = `Source unavailable: ${resolved.reason}`;
    } else {
      const recomputed = sha256Hex(resolved.bytes);
      if (recomputed === ev.contentHash) {
        status = "verified";
        note = "MATCH: recomputed hash equals the recorded content hash.";
      } else {
        status = "INTEGRITY_MISMATCH";
        note = `INTEGRITY_MISMATCH: recomputed ${recomputed} != recorded ${ev.contentHash}`;
      }
    }
  }

  ev.integrityStatus = status;
  ev.verificationNote = note;
  ev.checkCount += 1;
  ev.lastVerifiedAt = now;
  await ev.save();

  await logAction({
    entityType: "evidence",
    entityId: ev._id,
    action:
      status === "verified"
        ? "verified"
        : status === "INTEGRITY_MISMATCH"
          ? "tampered"
          : status === "unavailable"
            ? "unavailable"
            : "unverified",
    ...(actorId ? { actorId } : {}),
    payload: { integrityStatus: status, checkCount: ev.checkCount, note },
  });

  return {
    id: ev._id.toString(),
    integrityStatus: status,
    checkCount: ev.checkCount,
    lastVerifiedAt: now,
    verificationNote: note,
  };
}

// ── Verify all rows (dashboard "check all") ─────────────────────────────────
// Sequential, deterministic, never parallel — a single slow/failing source must
// not starve the rest. Failures are counted, never thrown.
export interface VerifyAllSummary {
  checked: number;
  verified: number;
  mismatched: number;
  unavailable: number;
  unverified: number;
  uploadFailed: number;
  failed: number;
}

export async function verifyAllEvidence(opts: {
  siteId?: Types.ObjectId;
  actorId?: Types.ObjectId;
} = {}): Promise<VerifyAllSummary> {
  const filter: Record<string, unknown> = {};
  if (opts.siteId) filter.siteId = opts.siteId;

  const rows = await Evidence.find(filter).select("_id").lean();
  const out: VerifyAllSummary = {
    checked: 0,
    verified: 0,
    mismatched: 0,
    unavailable: 0,
    unverified: 0,
    uploadFailed: 0,
    failed: 0,
  };

  for (const row of rows) {
    try {
      const r = await verifyEvidence(row._id as Types.ObjectId, opts.actorId);
      if (!r) {
        out.failed += 1;
        continue;
      }
      out.checked += 1;
      if (r.integrityStatus === "verified") out.verified += 1;
      else if (r.integrityStatus === "INTEGRITY_MISMATCH") out.mismatched += 1;
      else if (r.integrityStatus === "unavailable") out.unavailable += 1;
      else if (r.integrityStatus === "UPLOAD_FAILED") out.uploadFailed += 1;
      else out.unverified += 1;
    } catch {
      out.failed += 1;
    }
  }

  return out;
}