import PDFDocument from "pdfkit";
import Site from "../models/Site.js";
import Inspection from "../models/Inspection.js";
import Incident from "../models/Incident.js";
import Attendance from "../models/Attendance.js";
import Alert from "../models/Alert.js";
import type { InspectionType, AlertSeverity, IncidentSeverity } from "../types/index.js";

// ── Statutory Report Service ────────────────────────────────────────────────
// PRD FR7 — generates a legally-styled statutory compliance PDF (A4) for a
// single site over a date window. All figures come from the same operational
// collections that feed the rule engine and the hash-chained audit trail, so
// a report and its audit entry describe the same records.

export type ReportType = "comprehensive" | "safety" | "environmental" | "attendance";

export interface ReportParams {
  siteId: string;
  type: ReportType;
  from: Date;
  to: Date;
  generatedBy: string;
}

const fmtDate = (d: Date): string => d.toISOString().slice(0, 10);
const ACCENT = "#B45309";
const HEADING = "#1C2833";
const FONT_FAMILY = "Helvetica";

// ── Data ingestion ───────────────────────────────────────────────────────────

interface ReportData {
  site: {
    name: string;
    subsidiary: string;
    location: { lat: number; lng: number };
  };
  inspections: Array<{
    type: InspectionType;
    capturedAt: Date;
    checklist: Array<{ item: string; result: "pass" | "fail" | "na" }>;
  }>;
  incidents: Array<{
    category: string;
    severity: IncidentSeverity;
    description: string;
    capturedAt: Date;
  }>;
  attendanceCount: number;
  alerts: Array<{
    ruleCode: string;
    severity: AlertSeverity;
    status: string;
    createdAt: Date;
  }>;
}

async function gatherData(params: ReportParams): Promise<ReportData> {
  const [site, inspections, incidents, attendanceCount, alerts] = await Promise.all([
    Site.findById(params.siteId).lean(),
    Inspection.find({
      siteId: params.siteId,
      capturedAt: { $gte: params.from, $lte: params.to },
    })
      .select("type capturedAt checklist")
      .lean(),
    Incident.find({
      siteId: params.siteId,
      capturedAt: { $gte: params.from, $lte: params.to },
    })
      .select("category severity description capturedAt")
      .lean(),
    Attendance.countDocuments({
      siteId: params.siteId,
      capturedAt: { $gte: params.from, $lte: params.to },
    }),
    Alert.find({
      siteId: params.siteId,
      createdAt: { $gte: params.from, $lte: params.to },
    })
      .select("ruleCode severity status createdAt")
      .lean(),
  ]);

  if (!site) throw new Error(`Site not found: ${params.siteId}`);

  const s = site as unknown as {
    name: string;
    subsidiary: string;
    location: { lat: number; lng: number };
  };

  return {
    site: s,
    inspections: inspections as unknown as ReportData["inspections"],
    incidents: incidents as unknown as ReportData["incidents"],
    attendanceCount,
    alerts: alerts as unknown as ReportData["alerts"],
  };
}

// ── PDF rendering helpers ────────────────────────────────────────────────────

function drawHeader(
  doc: PDFKit.PDFDocument,
  data: ReportData,
  params: ReportParams
): void {
  doc
    .font(FONT_FAMILY)
    .fontSize(8)
    .fillColor(ACCENT)
    .text("GOVERNMENT OF INDIA", { align: "center" })
    .fontSize(14)
    .fillColor(HEADING)
    .text("MINISTRY OF COAL — STATUTORY COMPLIANCE REPORT", { align: "center" })
    .fontSize(9)
    .fillColor("#5B6770")
    .moveUp(0.25)
    .text("AgniStrot Smart Governance Platform", { align: "center" })
    .moveDown(1);

  doc
    .fontSize(10)
    .fillColor(HEADING)
    .text(`Mine: ${data.site.name}`)
    .fontSize(9)
    .fillColor("#37474F")
    .text(`Subsidiary: ${data.site.subsidiary}`)
    .text(
      `Geo-coordinates: ${data.site.location.lat.toFixed(5)}, ${data.site.location.lng.toFixed(5)}`
    )
    .text(
      `Reporting Window: From ${fmtDate(params.from)} to ${fmtDate(params.to)}`
    )
    .text(
      `Report Type: ${params.type.toUpperCase()}   |   Generated At: ${new Date().toISOString()}   |   Generated By: ${params.generatedBy}`
    )
    .moveDown(0.5);
}

function drawKpiSection(doc: PDFKit.PDFDocument, data: ReportData): void {
  doc
    .font(FONT_FAMILY)
    .fontSize(12)
    .fillColor(ACCENT)
    .text("EXECUTIVE SUMMARY", { underline: true })
    .moveDown(0.4);

  const failedCount = data.inspections.reduce(
    (sum, i) => sum + i.checklist.filter((c) => c.result === "fail").length,
    0
  );
  const passCount = data.inspections.reduce(
    (sum, i) => sum + i.checklist.filter((c) => c.result === "pass").length,
    0
  );

  const bySeverity: Record<IncidentSeverity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
  };
  for (const inc of data.incidents) bySeverity[inc.severity]++;

  const openAlerts = data.alerts.filter((a) => a.status === "open" || a.status === "acknowledged").length;
  const closedAlerts = data.alerts.filter((a) => a.status === "closed").length;
  const escalatedAlerts = data.alerts.filter((a) => a.status === "escalated").length;

  const rows: Array<[string, string]> = [
    ["Total Inspections", String(data.inspections.length)],
    ["Checklist Items — Pass / Fail", `${passCount} / ${failedCount}`],
    ["Total Incidents Reported", String(data.incidents.length)],
    ["  Critical / High / Medium / Low", `${bySeverity.critical} / ${bySeverity.high} / ${bySeverity.medium} / ${bySeverity.low}`],
    ["Attendance Entries Logged", String(data.attendanceCount)],
    ["Alerts — Open+ACK / Closed / Escalated", `${openAlerts} / ${closedAlerts} / ${escalatedAlerts}`],
  ];

  let y = doc.y;
  for (const [label, value] of rows) {
    doc
      .fontSize(9)
      .fillColor("#37474F")
      .text(label, 60, y, { width: 320 })
      .font(FONT_FAMILY).fontSize(9)
      .fillColor(HEADING)
      .text(value, 380, y, { width: 200, align: "right" });
    doc.moveDown(0.15);
    y = doc.y;
  }
  doc.moveDown(0.5);
}

function drawTableHeader(
  doc: PDFKit.PDFDocument,
  cols: Array<{ label: string; x: number; width: number }>
): void {
  doc
    .font(FONT_FAMILY)
    .fontSize(8)
    .fillColor("#FFFFFF")
    .rect(40, doc.y, 515, 14)
    .fill(ACCENT);
  const top = doc.y;
  for (const c of cols) {
    doc.fillColor("#FFFFFF");
    // padding tweak: draw label at x+2 baseline
    doc.text(c.label, c.x + 3, top + 3.5, { width: c.width, ellipsis: true });
  }
  doc.moveDown(0.5);
}

function drawTableRow(
  doc: PDFKit.PDFDocument,
  cells: Array<{ text: string; x: number; width: number }>,
  fill: string | null
): void {
  if (fill) doc.rect(40, doc.y, 515, 14).fill(fill);
  const top = doc.y;
  for (const c of cells) {
    doc.fillColor("#1F2933").fontSize(8);
    doc.text(c.text, c.x + 3, top + 3.5, { width: c.width, ellipsis: true, lineBreak: false });
  }
  doc.moveDown(0.15);
}

const sectionTitle = (doc: PDFKit.PDFDocument, title: string): void => {
  doc
    .font(FONT_FAMILY)
    .fontSize(11)
    .fillColor(ACCENT)
    .text(title, { underline: true })
    .moveDown(0.4);
};

// ── Detailed findings ────────────────────────────────────────────────────────

function drawCriticalIncidents(doc: PDFKit.PDFDocument, data: ReportData): void {
  const critical = data.incidents.filter((i) => i.severity === "critical" || i.severity === "high");
  if (critical.length === 0) {
    doc.font(FONT_FAMILY).fontSize(9).fillColor("#37474F").text("No critical or high-severity incidents in window.").moveDown(0.4);
    return;
  }
  const cols = [
    { label: "Date", x: 40, width: 70 },
    { label: "Category", x: 110, width: 80 },
    { label: "Severity", x: 190, width: 60 },
    { label: "Description", x: 250, width: 305 },
  ];
  drawTableHeader(doc, cols);
  for (const inc of critical) {
    drawTableRow(doc, [
      { text: fmtDate(inc.capturedAt), x: cols[0]!.x, width: cols[0]!.width },
      { text: inc.category, x: cols[1]!.x, width: cols[1]!.width },
      { text: inc.severity.toUpperCase(), x: cols[2]!.x, width: cols[2]!.width },
      { text: inc.description, x: cols[3]!.x, width: cols[3]!.width },
    ], null);
  }
  doc.moveDown(0.4);
}

function drawFailedChecklist(
  doc: PDFKit.PDFDocument,
  data: ReportData,
  onlyTypes: InspectionType[]
): void {
  const failed = data.inspections
    .filter((i) => onlyTypes.includes(i.type))
    .flatMap((insp) =>
      insp.checklist
        .filter((c) => c.result === "fail")
        .map((c) => ({ type: insp.type, capturedAt: insp.capturedAt, item: c.item }))
    );
  if (failed.length === 0) {
    doc.font(FONT_FAMILY).fontSize(9).fillColor("#37474F").text("No failed checklist items in window.").moveDown(0.4);
    return;
  }
  const cols = [
    { label: "Date", x: 40, width: 70 },
    { label: "Inspection", x: 110, width: 90 },
    { label: "Failed Checklist Item", x: 200, width: 355 },
  ];
  drawTableHeader(doc, cols);
  for (const f of failed) {
    drawTableRow(doc, [
      { text: fmtDate(f.capturedAt), x: cols[0]!.x, width: cols[0]!.width },
      { text: f.type.toUpperCase(), x: cols[1]!.x, width: cols[1]!.width },
      { text: f.item, x: cols[2]!.x, width: cols[2]!.width },
    ], null);
  }
  doc.moveDown(0.4);
}

function drawAlerts(doc: PDFKit.PDFDocument, data: ReportData): void {
  const active = data.alerts.filter((a) => a.status !== "closed");
  if (active.length === 0) {
    doc.font(FONT_FAMILY).fontSize(9).fillColor("#37474F").text("No open compliance alerts in window.").moveDown(0.4);
    return;
  }
  const cols = [
    { label: "Created", x: 40, width: 70 },
    { label: "Rule", x: 110, width: 170 },
    { label: "Severity", x: 290, width: 70 },
    { label: "Status", x: 360, width: 195 },
  ];
  drawTableHeader(doc, cols);
  for (const a of active.slice(0, 25)) {
    drawTableRow(doc, [
      { text: fmtDate(a.createdAt), x: cols[0]!.x, width: cols[0]!.width },
      { text: a.ruleCode, x: cols[1]!.x, width: cols[1]!.width },
      { text: a.severity.toUpperCase(), x: cols[2]!.x, width: cols[2]!.width },
      { text: a.status.toUpperCase(), x: cols[3]!.x, width: cols[3]!.width },
    ], null);
  }
  doc.moveDown(0.4);
}

function drawAttendance(doc: PDFKit.PDFDocument, data: ReportData): void {
  doc
    .font(FONT_FAMILY)
    .fontSize(10)
    .fillColor("#37474F")
    .text(
      `Total attendance entries logged in window: ${data.attendanceCount}`
    )
    .moveDown(0.4);
}

// ── Document builder ─────────────────────────────────────────────────────────

export async function buildStatutoryPdf(params: ReportParams): Promise<Buffer> {
  const data = await gatherData(params);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("error", (err: Error) => reject(err));

    // Page-count stamping happens once the final page count is known.
    doc.on("end", () => {
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        const page = doc.page;
        doc
          .font(FONT_FAMILY)
          .fontSize(7.5)
          .fillColor("#8A939A")
          .text(
            "Generated from immutable hash-chained operational records.",
            40,
            page.height - 28,
            { align: "center", width: page.width - 80 }
          )
          .text(`Page ${i + 1} of ${range.count}`, 40, page.height - 40, {
            align: "right",
            width: page.width - 80,
          });
      }
      resolve(Buffer.concat(chunks));
    });

    drawHeader(doc, data, params);
    drawKpiSection(doc, data);
    sectionTitle(doc, "DETAILED FINDINGS");

    if (params.type === "comprehensive" || params.type === "safety") {
      sectionTitle(doc, "Critical & High Severity Incidents");
      drawCriticalIncidents(doc, data);
    }
    if (params.type === "comprehensive") {
      sectionTitle(doc, "Failed Checklist Items — Safety Inspections");
      drawFailedChecklist(doc, data, ["safety"]);
      sectionTitle(doc, "Failed Checklist Items — Environmental Inspections");
      drawFailedChecklist(doc, data, ["environmental"]);
    }
    if (params.type === "safety") {
      sectionTitle(doc, "Failed Checklist Items — Safety & Environmental Inspections");
      drawFailedChecklist(doc, data, ["safety", "environmental"]);
    }
    if (params.type === "environmental") {
      sectionTitle(doc, "Failed Checklist Items — Environmental Inspections");
      drawFailedChecklist(doc, data, ["environmental"]);
    }
    if (params.type === "attendance") {
      sectionTitle(doc, "Attendance Summary");
      drawAttendance(doc, data);
    }

    sectionTitle(doc, "Open Compliance Issues & Escalations");
    drawAlerts(doc, data);

    doc.end();
  });
}